server:
  persistentVolume:
    size: 10Gi
  retention: 15d
  service:
    type: LoadBalancer
  ingress:
    enabled: false
  
alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

global:
  scrape_interval: 15s
  evaluation_interval: 15s

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'otel-collector-azure'
        static_configs:
          - targets: ['azure-documentdb-collector.documentdb-preview-ns.svc.cluster.local:8889']
            labels:
              service: 'documentdb-gateway'
              region: 'azure'
      - job_name: 'otel-collector-aws'
        static_configs:
          - targets: ['aws-documentdb-collector.documentdb-preview-ns.svc.cluster.local:8889']
            labels:
              service: 'documentdb-gateway'
              region: 'aws'
      - job_name: 'otel-collector-westus'
        static_configs:
          - targets: ['gcp-documentdb-collector.documentdb-preview-ns.svc.cluster.local:8889']
            labels:
              service: 'documentdb-gateway'
              region: 'gcp'
      
      # Prometheus self-monitoring
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']